default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: true_budget_dev

test:
  <<: *default
  database: true_budget_test

#production:
#  <<: *default
#  database: true_budget_prod
